language: python

env:
  global:
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm
    - HELM_TGZ=helm-v2.14.3-linux-amd64.tar.gz
    - TARGET_BR=gh-pages
    - GH_URL=https://submariner-io.github.io/submariner-charts/charts
    - CHARTS_DIR=charts
    - YAMLLINT_VERSION=1.17.0

install:
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only
  - sudo pip install yamllint=="${YAMLLINT_VERSION}"

script:
  - for dir in submariner submariner-k8s-broker; do helm lint $dir; done
  - yamllint -c .yamllint.yml -s $(find . -type f -name "Chart.yaml")
  - yamllint -c .yamllint.yml -s $(find . -type f -name "values.yaml")

after_success:
  - >
    if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      for dir in submariner submariner-k8s-broker; do
        helm dep update $dir
        helm package $dir
      done
      REPO_URL=`git config remote.origin.url`
      git clone ${REPO_URL} out && cd out && git checkout gh-pages && mkdir -p ${CHARTS_DIR}
      cp -f ../submariner-*.tgz ${CHARTS_DIR}/
      if [ -f charts/index.yaml ]; then
        helm repo index ${CHARTS_DIR} --url ${GH_URL} --merge index.yaml
      else
        helm repo index ${CHARTS_DIR} --url ${GH_URL}
      fi
      git config user.name "Travis CI"
      git config user.email "travis@travis-ci.org"
      git add -f ${CHARTS_DIR}/*
      git commit -m "Travis build: $TRAVIS_BUILD_NUMBER"
      git remote add origin-pages https://${GH_TOKEN}@github.com/submariner-io/submariner-charts.git > /dev/null 2>&1
      git push --quiet -f -u origin-pages gh-pages
    fi
