---
submariner:
  clusterId: ""
  token: ""
  clusterCidr: ""
  serviceCidr: ""
  globalCidr: ""
  loadBalancerEnabled: false
  natEnabled: false
  colorCodes: blue
  debug: false
  serviceDiscovery: true
  cableDriver: "libreswan"
  healthcheckEnabled: true
  coreDNSCustomConfig: {}
  images:
    repository: quay.io/submariner
    tag: "0.14.0-m1"
broker:
  server: example.k8s.apiserver
  token: test
  namespace: xyz
  insecure: false
  ca: ""
  globalnet: false
rbac:
  create: true
images: {}
ipsec:
  psk: ""
  debug: false
  forceUDPEncaps: false
  ikePort: 500
  natPort: 4500
leadership:
  leaseDuration: 10
  renewDeadline: 5
  retryPeriod: 2
operator:
  image:
    repository: quay.io/submariner/submariner-operator
    tag: "0.14.0-m1"
    pullPolicy: IfNotPresent
  resources: {}
  tolerations: []
  affinity: {}
gateway:
  image:
    repository: quay.io/submariner/submariner-gateway
    tag: "0.14.0-m1"
serviceAccounts:
  operator:
    create: true
    name: ""
  gateway:
    create: true
    name: ""
  routeAgent:
    create: true
    name: ""
  globalnet:
    create: true
    name: ""
  lighthouseAgent:
    create: true
    name: ""
  lighthouseCoreDns:
    create: true
    name: ""
